// Code generated by zajson. DO NOT EDIT.

package types

import (
	"github.com/pedidopago/zajson"
	"slices"
	"strings"
	"time"
)

func (v *ContactMetadata) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.InquiryID != nil {
		w.WriteCommaFieldName(",\"inquiry_id\":")
		w.WriteQuotedString((*v.InquiryID))
	}
	if v.InquiryStatus != nil {
		w.WriteCommaFieldName(",\"inquiry_status\":")
		w.WriteQuotedString((*v.InquiryStatus))
	}
	if v.InquiryDisplayID != nil {
		w.WriteCommaFieldName(",\"inquiry_display_id\":")
		w.WriteQuotedString((*v.InquiryDisplayID))
	}
	if v.InquiryAgentID != nil {
		w.WriteCommaFieldName(",\"inquiry_agent_id\":")
		w.WriteQuotedString((*v.InquiryAgentID))
	}
	if v.InquiryAgentName != nil {
		w.WriteCommaFieldName(",\"inquiry_agent_name\":")
		w.WriteQuotedString((*v.InquiryAgentName))
	}
	if v.InquiryAIEvaluation != nil {
		w.WriteCommaFieldName(",\"inquiry_ai_evaluation\":")
		w.WriteQuotedString((*v.InquiryAIEvaluation))
	}
	if v.InquiryCanBindDisplayID != nil {
		w.WriteCommaFieldName(",\"inquiry_can_bind_display_id\":")
		w.WriteBool((*v.InquiryCanBindDisplayID))
	}
	if v.InquiryCreatedAt != nil {
		w.WriteCommaFieldName(",\"inquiry_created_at\":")
		w.WriteRFC3339Nano((*v.InquiryCreatedAt))
	}
	if v.InquiryExpireDate != nil {
		w.WriteCommaFieldName(",\"inquiry_expire_date\":")
		w.WriteRFC3339Nano((*v.InquiryExpireDate))
	}
	if v.InquirySellerAgentID != nil {
		w.WriteCommaFieldName(",\"inquiry_seller_agent_id\":")
		w.WriteQuotedString((*v.InquirySellerAgentID))
	}
	if v.InquirySellerAgentName != nil {
		w.WriteCommaFieldName(",\"inquiry_seller_agent_name\":")
		w.WriteQuotedString((*v.InquirySellerAgentName))
	}
	if v.InquiryHasPendencies != nil {
		w.WriteCommaFieldName(",\"inquiry_has_pendencies\":")
		w.WriteBool((*v.InquiryHasPendencies))
	}
	if v.InquirySellOpportunityCollected != nil {
		w.WriteCommaFieldName(",\"inquiry_sell_opportunity_collected\":")
		w.WriteBool((*v.InquirySellOpportunityCollected))
	}
	if v.InquiryQuotatedAt != nil {
		w.WriteCommaFieldName(",\"inquiry_quotated_at\":")
		w.WriteRFC3339Nano((*v.InquiryQuotatedAt))
	}
	if v.InquiryDoneAt != nil {
		w.WriteCommaFieldName(",\"inquiry_done_at\":")
		w.WriteRFC3339Nano((*v.InquiryDoneAt))
	}
	if v.InquiryLastStatusUpdate != nil {
		w.WriteCommaFieldName(",\"inquiry_last_status_update\":")
		w.WriteRFC3339Nano((*v.InquiryLastStatusUpdate))
	}
	if v.InquiryIsChatOpen != nil {
		w.WriteCommaFieldName(",\"inquiry_is_chat_open\":")
		w.WriteBool((*v.InquiryIsChatOpen))
	}
	if v.InquiryIsMarketplace != nil {
		w.WriteCommaFieldName(",\"inquiry_is_marketplace\":")
		w.WriteBool((*v.InquiryIsMarketplace))
	}
	if v.InquiryInclusorAgentID != nil {
		w.WriteCommaFieldName(",\"inquiry_inclusor_agent_id\":")
		w.WriteQuotedString((*v.InquiryInclusorAgentID))
	}
	if v.InquiryInclusorAgentName != nil {
		w.WriteCommaFieldName(",\"inquiry_inclusor_agent_name\":")
		w.WriteQuotedString((*v.InquiryInclusorAgentName))
	}
	if v.InquirySpecialistAgentID != nil {
		w.WriteCommaFieldName(",\"inquiry_specialist_agent_id\":")
		w.WriteQuotedString((*v.InquirySpecialistAgentID))
	}
	if v.InquirySpecialistAgentName != nil {
		w.WriteCommaFieldName(",\"inquiry_specialist_agent_name\":")
		w.WriteQuotedString((*v.InquirySpecialistAgentName))
	}
	if v.AccountID != nil {
		w.WriteCommaFieldName(",\"account_id\":")
		w.WriteQuotedString((*v.AccountID))
	}
	if v.ChatbotDisabled != nil {
		w.WriteCommaFieldName(",\"chatbot_disabled\":")
		w.WriteBool((*v.ChatbotDisabled))
	}
	if v.ChatbotInitialContact != nil {
		w.WriteCommaFieldName(",\"chatbot_initial_contact\":")
		w.WriteRFC3339Nano((*v.ChatbotInitialContact))
	}
	if v.ChatbotIsPreRegistration != nil {
		w.WriteCommaFieldName(",\"chatbot_is_pre_registration\":")
		w.WriteBool((*v.ChatbotIsPreRegistration))
	}
	if v.ChatbotLastState != nil {
		w.WriteCommaFieldName(",\"chatbot_last_state\":")
		w.WriteQuotedString((*v.ChatbotLastState))
	}
	if v.ChatbotRegistrationDate != nil {
		w.WriteCommaFieldName(",\"chatbot_registration_date\":")
		w.WriteRFC3339Nano((*v.ChatbotRegistrationDate))
	}
	if v.SkipWelcome != nil {
		w.WriteCommaFieldName(",\"skip_welcome\":")
		w.WriteBool((*v.SkipWelcome))
	}
	if v.MarketingDisabledReason != nil {
		w.WriteCommaFieldName(",\"marketing_disabled_reason\":")
		w.WriteQuotedString((*v.MarketingDisabledReason))
	}
	if v.InitialContactChannel != nil {
		w.WriteCommaFieldName(",\"initial_contact_channel\":")
		w.WriteQuotedString((*v.InitialContactChannel))
	}
	if v.InitialContactDate != nil {
		w.WriteCommaFieldName(",\"initial_contact_date\":")
		w.WriteRFC3339Nano((*v.InitialContactDate))
	}
	if v.CustomerName != nil {
		w.WriteCommaFieldName(",\"customer_name\":")
		w.WriteQuotedString((*v.CustomerName))
	}
	if v.CustomerDocumentCountry != nil {
		w.WriteCommaFieldName(",\"customer_document_country\":")
		w.WriteQuotedString((*v.CustomerDocumentCountry))
	}
	if v.CustomerDocumentType != nil {
		w.WriteCommaFieldName(",\"customer_document_type\":")
		w.WriteQuotedString((*v.CustomerDocumentType))
	}
	if v.CustomerDocument != nil {
		w.WriteCommaFieldName(",\"customer_document\":")
		w.WriteQuotedString((*v.CustomerDocument))
	}
	if v.LastOrderSeq != nil {
		w.WriteCommaFieldName(",\"last_order_seq\":")
		w.WriteInt64(int64((*v.LastOrderSeq)))
	}
	if v.LastCouponOffered != nil {
		w.WriteCommaFieldName(",\"last_coupon_offered\":")
		w.WriteQuotedString((*v.LastCouponOffered))
	}
	if v.Order != nil {
		w.WriteCommaFieldName(",\"order\":")
		if err := (*v.Order).ZMarshalJSON(w); err != nil {
			return err
		}
	}
	if v.Prescription != nil {
		w.WriteCommaFieldName(",\"prescription\":")
		if err := (*v.Prescription).ZMarshalJSON(w); err != nil {
			return err
		}
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "inquiry_id", "inquiry_status", "inquiry_display_id", "inquiry_agent_id", "inquiry_agent_name", "inquiry_ai_evaluation", "inquiry_can_bind_display_id", "inquiry_created_at", "inquiry_expire_date", "inquiry_seller_agent_id", "inquiry_seller_agent_name", "inquiry_has_pendencies", "inquiry_sell_opportunity_collected", "inquiry_quotated_at", "inquiry_done_at", "inquiry_last_status_update", "inquiry_is_chat_open", "inquiry_is_marketplace", "inquiry_inclusor_agent_id", "inquiry_inclusor_agent_name", "inquiry_specialist_agent_id", "inquiry_specialist_agent_name", "account_id", "chatbot_disabled", "chatbot_initial_contact", "chatbot_is_pre_registration", "chatbot_last_state", "chatbot_registration_date", "skip_welcome", "marketing_disabled_reason", "initial_contact_channel", "initial_contact_date", "customer_name", "customer_document_country", "customer_document_type", "customer_document", "last_order_seq", "last_coupon_offered", "order", "prescription":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *ContactMetadata) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "inquiry_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryID = nil
			} else {
				_ptr := new(string)
				v.InquiryID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryID) = strings.Clone(_val)
				}
			}
		case "inquiry_status":
			{
				_val, _err := ZReadInquiryStatus(r)
				if _err != nil {
					return _err
				}
				v.InquiryStatus = _val
			}
		case "inquiry_display_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryDisplayID = nil
			} else {
				_ptr := new(string)
				v.InquiryDisplayID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryDisplayID) = strings.Clone(_val)
				}
			}
		case "inquiry_agent_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryAgentID = nil
			} else {
				_ptr := new(string)
				v.InquiryAgentID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryAgentID) = strings.Clone(_val)
				}
			}
		case "inquiry_agent_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryAgentName = nil
			} else {
				_ptr := new(string)
				v.InquiryAgentName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryAgentName) = strings.Clone(_val)
				}
			}
		case "inquiry_ai_evaluation":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryAIEvaluation = nil
			} else {
				_ptr := new(string)
				v.InquiryAIEvaluation = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryAIEvaluation) = strings.Clone(_val)
				}
			}
		case "inquiry_can_bind_display_id":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.InquiryCanBindDisplayID = _val
			}
		case "inquiry_created_at":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryCreatedAt = nil
			} else {
				_ptr := new(time.Time)
				v.InquiryCreatedAt = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InquiryCreatedAt) = _t
				}
			}
		case "inquiry_expire_date":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryExpireDate = nil
			} else {
				_ptr := new(time.Time)
				v.InquiryExpireDate = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InquiryExpireDate) = _t
				}
			}
		case "inquiry_seller_agent_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquirySellerAgentID = nil
			} else {
				_ptr := new(string)
				v.InquirySellerAgentID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquirySellerAgentID) = strings.Clone(_val)
				}
			}
		case "inquiry_seller_agent_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquirySellerAgentName = nil
			} else {
				_ptr := new(string)
				v.InquirySellerAgentName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquirySellerAgentName) = strings.Clone(_val)
				}
			}
		case "inquiry_has_pendencies":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.InquiryHasPendencies = _val
			}
		case "inquiry_sell_opportunity_collected":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.InquirySellOpportunityCollected = _val
			}
		case "inquiry_quotated_at":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryQuotatedAt = nil
			} else {
				_ptr := new(time.Time)
				v.InquiryQuotatedAt = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InquiryQuotatedAt) = _t
				}
			}
		case "inquiry_done_at":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryDoneAt = nil
			} else {
				_ptr := new(time.Time)
				v.InquiryDoneAt = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InquiryDoneAt) = _t
				}
			}
		case "inquiry_last_status_update":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryLastStatusUpdate = nil
			} else {
				_ptr := new(time.Time)
				v.InquiryLastStatusUpdate = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InquiryLastStatusUpdate) = _t
				}
			}
		case "inquiry_is_chat_open":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.InquiryIsChatOpen = _val
			}
		case "inquiry_is_marketplace":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.InquiryIsMarketplace = _val
			}
		case "inquiry_inclusor_agent_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryInclusorAgentID = nil
			} else {
				_ptr := new(string)
				v.InquiryInclusorAgentID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryInclusorAgentID) = strings.Clone(_val)
				}
			}
		case "inquiry_inclusor_agent_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquiryInclusorAgentName = nil
			} else {
				_ptr := new(string)
				v.InquiryInclusorAgentName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquiryInclusorAgentName) = strings.Clone(_val)
				}
			}
		case "inquiry_specialist_agent_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquirySpecialistAgentID = nil
			} else {
				_ptr := new(string)
				v.InquirySpecialistAgentID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquirySpecialistAgentID) = strings.Clone(_val)
				}
			}
		case "inquiry_specialist_agent_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InquirySpecialistAgentName = nil
			} else {
				_ptr := new(string)
				v.InquirySpecialistAgentName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.InquirySpecialistAgentName) = strings.Clone(_val)
				}
			}
		case "account_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.AccountID = nil
			} else {
				_ptr := new(string)
				v.AccountID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.AccountID) = strings.Clone(_val)
				}
			}
		case "chatbot_disabled":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.ChatbotDisabled = _val
			}
		case "chatbot_initial_contact":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.ChatbotInitialContact = nil
			} else {
				_ptr := new(time.Time)
				v.ChatbotInitialContact = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.ChatbotInitialContact) = _t
				}
			}
		case "chatbot_is_pre_registration":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.ChatbotIsPreRegistration = _val
			}
		case "chatbot_last_state":
			{
				_val, _err := ZReadChatbotLastState(r)
				if _err != nil {
					return _err
				}
				v.ChatbotLastState = _val
			}
		case "chatbot_registration_date":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.ChatbotRegistrationDate = nil
			} else {
				_ptr := new(time.Time)
				v.ChatbotRegistrationDate = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.ChatbotRegistrationDate) = _t
				}
			}
		case "skip_welcome":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.SkipWelcome = _val
			}
		case "marketing_disabled_reason":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.MarketingDisabledReason = nil
			} else {
				_ptr := new(string)
				v.MarketingDisabledReason = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.MarketingDisabledReason) = strings.Clone(_val)
				}
			}
		case "initial_contact_channel":
			{
				_val, _err := ZReadInitialContactChannel(r)
				if _err != nil {
					return _err
				}
				v.InitialContactChannel = _val
			}
		case "initial_contact_date":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.InitialContactDate = nil
			} else {
				_ptr := new(time.Time)
				v.InitialContactDate = _ptr
				{
					_s, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					_t, _err := time.Parse(time.RFC3339Nano, _s)
					if _err != nil {
						return _err
					}
					(*v.InitialContactDate) = _t
				}
			}
		case "customer_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.CustomerName = nil
			} else {
				_ptr := new(string)
				v.CustomerName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.CustomerName) = strings.Clone(_val)
				}
			}
		case "customer_document_country":
			{
				_val, _err := ZReadCustomerDocumentCountry(r)
				if _err != nil {
					return _err
				}
				v.CustomerDocumentCountry = _val
			}
		case "customer_document_type":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.CustomerDocumentType = nil
			} else {
				_ptr := new(string)
				v.CustomerDocumentType = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.CustomerDocumentType) = strings.Clone(_val)
				}
			}
		case "customer_document":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.CustomerDocument = nil
			} else {
				_ptr := new(string)
				v.CustomerDocument = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.CustomerDocument) = strings.Clone(_val)
				}
			}
		case "last_order_seq":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.LastOrderSeq = nil
			} else {
				_ptr := new(int)
				v.LastOrderSeq = _ptr
				{
					_val, _err := r.ReadInt64()
					if _err != nil {
						return _err
					}
					(*v.LastOrderSeq) = int(_val)
				}
			}
		case "last_coupon_offered":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.LastCouponOffered = nil
			} else {
				_ptr := new(string)
				v.LastCouponOffered = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.LastCouponOffered) = strings.Clone(_val)
				}
			}
		case "order":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Order = nil
			} else {
				_ptr := new(ContactMetadataOrder)
				v.Order = _ptr
				if _err := (*v.Order).ZUnmarshalJSON(r); _err != nil {
					return _err
				}
			}
		case "prescription":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Prescription = nil
			} else {
				_ptr := new(ContactMetadataPrescription)
				v.Prescription = _ptr
				if _err := (*v.Prescription).ZUnmarshalJSON(r); _err != nil {
					return _err
				}
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}

func (v *ContactMetadataOrder) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.Status != nil {
		w.WriteCommaFieldName(",\"status\":")
		w.WriteQuotedString((*v.Status))
	}
	if v.Prescription != nil {
		w.WriteCommaFieldName(",\"prescription\":")
		if err := (*v.Prescription).ZMarshalJSON(w); err != nil {
			return err
		}
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "status", "prescription":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *ContactMetadataOrder) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "status":
			{
				_val, _err := ZReadOrderStatus(r)
				if _err != nil {
					return _err
				}
				v.Status = _val
			}
		case "prescription":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Prescription = nil
			} else {
				_ptr := new(OrderPrescription)
				v.Prescription = _ptr
				if _err := (*v.Prescription).ZUnmarshalJSON(r); _err != nil {
					return _err
				}
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}

func (v *OrderPrescription) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.IsMedical != nil {
		w.WriteCommaFieldName(",\"is_medical\":")
		w.WriteBool((*v.IsMedical))
	}
	if v.Retained != nil {
		w.WriteCommaFieldName(",\"retained\":")
		w.WriteBool((*v.Retained))
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "is_medical", "retained":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *OrderPrescription) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "is_medical":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.IsMedical = _val
			}
		case "retained":
			{
				_val, _err := ZReadMetadataBool(r)
				if _err != nil {
					return _err
				}
				v.Retained = _val
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}

func (v *ContactMetadataPrescription) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.ID != nil {
		w.WriteCommaFieldName(",\"id\":")
		w.WriteQuotedString((*v.ID))
	}
	if v.DisplayID != nil {
		w.WriteCommaFieldName(",\"display_id\":")
		w.WriteQuotedString((*v.DisplayID))
	}
	if v.DoctorID != nil {
		w.WriteCommaFieldName(",\"doctor_id\":")
		w.WriteQuotedString((*v.DoctorID))
	}
	if v.Customer != nil {
		w.WriteCommaFieldName(",\"customer\":")
		if err := (*v.Customer).ZMarshalJSON(w); err != nil {
			return err
		}
	}
	if v.FileURL != nil {
		w.WriteCommaFieldName(",\"file_url\":")
		w.WriteQuotedString((*v.FileURL))
	}
	if v.PresellerID != nil {
		w.WriteCommaFieldName(",\"preseller_id\":")
		w.WriteQuotedString((*v.PresellerID))
	}
	if v.PresellerName != nil {
		w.WriteCommaFieldName(",\"preseller_name\":")
		w.WriteQuotedString((*v.PresellerName))
	}
	if v.Observation != nil {
		w.WriteCommaFieldName(",\"observation\":")
		w.WriteQuotedString((*v.Observation))
	}
	if v.ObservationAuthor != nil {
		w.WriteCommaFieldName(",\"observation_author\":")
		w.WriteQuotedString((*v.ObservationAuthor))
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "id", "display_id", "doctor_id", "customer", "file_url", "preseller_id", "preseller_name", "observation", "observation_author":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *ContactMetadataPrescription) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.ID = nil
			} else {
				_ptr := new(string)
				v.ID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.ID) = strings.Clone(_val)
				}
			}
		case "display_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.DisplayID = nil
			} else {
				_ptr := new(string)
				v.DisplayID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.DisplayID) = strings.Clone(_val)
				}
			}
		case "doctor_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.DoctorID = nil
			} else {
				_ptr := new(string)
				v.DoctorID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.DoctorID) = strings.Clone(_val)
				}
			}
		case "customer":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Customer = nil
			} else {
				_ptr := new(PrescriptionCustomer)
				v.Customer = _ptr
				if _err := (*v.Customer).ZUnmarshalJSON(r); _err != nil {
					return _err
				}
			}
		case "file_url":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.FileURL = nil
			} else {
				_ptr := new(string)
				v.FileURL = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.FileURL) = strings.Clone(_val)
				}
			}
		case "preseller_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.PresellerID = nil
			} else {
				_ptr := new(string)
				v.PresellerID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.PresellerID) = strings.Clone(_val)
				}
			}
		case "preseller_name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.PresellerName = nil
			} else {
				_ptr := new(string)
				v.PresellerName = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.PresellerName) = strings.Clone(_val)
				}
			}
		case "observation":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Observation = nil
			} else {
				_ptr := new(string)
				v.Observation = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Observation) = strings.Clone(_val)
				}
			}
		case "observation_author":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.ObservationAuthor = nil
			} else {
				_ptr := new(string)
				v.ObservationAuthor = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.ObservationAuthor) = strings.Clone(_val)
				}
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}

func (v *PrescriptionCustomer) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.DoctorCustomerID != nil {
		w.WriteCommaFieldName(",\"doctor_customer_id\":")
		w.WriteQuotedString((*v.DoctorCustomerID))
	}
	if v.AccountID != nil {
		w.WriteCommaFieldName(",\"account_id\":")
		w.WriteQuotedString((*v.AccountID))
	}
	if v.CustomerID != nil {
		w.WriteCommaFieldName(",\"customer_id\":")
		w.WriteQuotedString((*v.CustomerID))
	}
	if v.Name != nil {
		w.WriteCommaFieldName(",\"name\":")
		w.WriteQuotedString((*v.Name))
	}
	if v.CPF != nil {
		w.WriteCommaFieldName(",\"cpf\":")
		w.WriteQuotedString((*v.CPF))
	}
	if v.Phone != nil {
		w.WriteCommaFieldName(",\"phone\":")
		w.WriteQuotedString((*v.Phone))
	}
	if v.Email != nil {
		w.WriteCommaFieldName(",\"email\":")
		w.WriteQuotedString((*v.Email))
	}
	if v.Birthdate != nil {
		w.WriteCommaFieldName(",\"birthdate\":")
		w.WriteQuotedString((*v.Birthdate))
	}
	if v.Address != nil {
		w.WriteCommaFieldName(",\"address\":")
		if err := (*v.Address).ZMarshalJSON(w); err != nil {
			return err
		}
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "doctor_customer_id", "account_id", "customer_id", "name", "cpf", "phone", "email", "birthdate", "address":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *PrescriptionCustomer) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "doctor_customer_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.DoctorCustomerID = nil
			} else {
				_ptr := new(string)
				v.DoctorCustomerID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.DoctorCustomerID) = strings.Clone(_val)
				}
			}
		case "account_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.AccountID = nil
			} else {
				_ptr := new(string)
				v.AccountID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.AccountID) = strings.Clone(_val)
				}
			}
		case "customer_id":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.CustomerID = nil
			} else {
				_ptr := new(string)
				v.CustomerID = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.CustomerID) = strings.Clone(_val)
				}
			}
		case "name":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Name = nil
			} else {
				_ptr := new(string)
				v.Name = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Name) = strings.Clone(_val)
				}
			}
		case "cpf":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.CPF = nil
			} else {
				_ptr := new(string)
				v.CPF = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.CPF) = strings.Clone(_val)
				}
			}
		case "phone":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Phone = nil
			} else {
				_ptr := new(string)
				v.Phone = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Phone) = strings.Clone(_val)
				}
			}
		case "email":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Email = nil
			} else {
				_ptr := new(string)
				v.Email = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Email) = strings.Clone(_val)
				}
			}
		case "birthdate":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Birthdate = nil
			} else {
				_ptr := new(string)
				v.Birthdate = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Birthdate) = strings.Clone(_val)
				}
			}
		case "address":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Address = nil
			} else {
				_ptr := new(PrescriptionCustomerAddress)
				v.Address = _ptr
				if _err := (*v.Address).ZUnmarshalJSON(r); _err != nil {
					return _err
				}
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}

func (v *PrescriptionCustomerAddress) ZMarshalJSON(w *zajson.Writer) error {
	w.BeginObject()
	if v.Country != nil {
		w.WriteCommaFieldName(",\"country\":")
		w.WriteQuotedString((*v.Country))
	}
	if v.Street != nil {
		w.WriteCommaFieldName(",\"street\":")
		w.WriteQuotedString((*v.Street))
	}
	if v.Number != nil {
		w.WriteCommaFieldName(",\"number\":")
		w.WriteQuotedString((*v.Number))
	}
	if v.Complement != nil {
		w.WriteCommaFieldName(",\"complement\":")
		w.WriteQuotedString((*v.Complement))
	}
	if v.City != nil {
		w.WriteCommaFieldName(",\"city\":")
		w.WriteQuotedString((*v.City))
	}
	if v.UF != nil {
		w.WriteCommaFieldName(",\"uf\":")
		w.WriteQuotedString((*v.UF))
	}
	if v.District != nil {
		w.WriteCommaFieldName(",\"district\":")
		w.WriteQuotedString((*v.District))
	}
	if v.Zip != nil {
		w.WriteCommaFieldName(",\"zip\":")
		w.WriteQuotedString((*v.Zip))
	}
	if v.OtherFields != nil {
		_rkeys := make([]string, 0, len(v.OtherFields))
		for _rk := range v.OtherFields {
			_rkeys = append(_rkeys, _rk)
		}
		slices.Sort(_rkeys)
		for _, _rk := range _rkeys {
			switch _rk {
			case "country", "street", "number", "complement", "city", "uf", "district", "zip":
				// skip: known field wins on collision
			default:
				w.WriteDynamicFieldName(_rk)
				w.WriteAny(v.OtherFields[_rk])
			}
		}
	}
	w.EndObject()
	return w.Err()
}

func (v *PrescriptionCustomerAddress) ZUnmarshalJSON(r *zajson.Reader) error {
	if _err := r.ReadObjectStart(); _err != nil {
		return _err
	}
	for {
		_key, _ok, _err := r.NextField()
		if _err != nil {
			return _err
		}
		if !_ok {
			return nil
		}
		switch _key {
		case "country":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Country = nil
			} else {
				_ptr := new(string)
				v.Country = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Country) = strings.Clone(_val)
				}
			}
		case "street":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Street = nil
			} else {
				_ptr := new(string)
				v.Street = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Street) = strings.Clone(_val)
				}
			}
		case "number":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Number = nil
			} else {
				_ptr := new(string)
				v.Number = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Number) = strings.Clone(_val)
				}
			}
		case "complement":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Complement = nil
			} else {
				_ptr := new(string)
				v.Complement = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Complement) = strings.Clone(_val)
				}
			}
		case "city":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.City = nil
			} else {
				_ptr := new(string)
				v.City = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.City) = strings.Clone(_val)
				}
			}
		case "uf":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.UF = nil
			} else {
				_ptr := new(string)
				v.UF = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.UF) = strings.Clone(_val)
				}
			}
		case "district":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.District = nil
			} else {
				_ptr := new(string)
				v.District = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.District) = strings.Clone(_val)
				}
			}
		case "zip":
			if r.PeekNull() {
				if _err := r.ReadNull(); _err != nil {
					return _err
				}
				v.Zip = nil
			} else {
				_ptr := new(string)
				v.Zip = _ptr
				{
					_val, _err := r.ReadString()
					if _err != nil {
						return _err
					}
					(*v.Zip) = strings.Clone(_val)
				}
			}
		default:
			if v.OtherFields == nil {
				v.OtherFields = make(map[string]any)
			}
			_any, _err := r.ReadAny()
			if _err != nil {
				return _err
			}
			v.OtherFields[_key] = _any
		}
		r.PopPath()
	}
}
