name: PR CIs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Retrieve Git Tokens
        env:
          USER: ${{ secrets.GIT_USER }}
          TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "git+ssh://git@github.com/pedidopago" --replace-all
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "https://github.com/pedidopago" --add
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.4
      - name: Run Tests
        run: |
          go test ./...
      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2
      - name: Run vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
